### PR TITLE
Backend refactoring

### PR DESCRIPTION
**Pull request by wmeints**
Hi edwin,  Gave the backend some love too. Hope you like what I did with the place. :-)

### CODE REVIEW

**Comment by wmeints** [comment]
Need to polish this some more I see. 
Turns out that I didn't add the dependency resolver. 

Instead of introducing stuff like Unity, I'm going to remove the constructor argument.
And possibly add a few tests to make sure that things work okay.

**Comment by EdwinVW** [comment]
Indeed, I missed the dependency resolver. But I already added it after pulling your code.

Another issue I found while testing your changes is that something goes wrong in the mapping code in *ReleaseDataService.MapReleaseData*. Every release in the result contains the stages and steps of the last release added to the collection. In my implementation I created new (dynamic) objects to build the result JSON and didn't experience this issue. 

Using dynamics and not creating a datamodel was an explicit choice by the way (imho the benefits do not justify the extra work of creating all these datamodel classes and loosing flexibility in defining the resulting datastructure).

**Comment by wmeints** [comment]
Weirdness, I wrote a test to validate that the serialization wasn't causing the problems. Turns out it is somewhere in the mapping code. Do you have time for a short debugging session on wednesday?

**Comment by EdwinVW** [comment]
Sure. I'm in Veenendaal on wednesday.

**Comment by wmeints** [comment]
Let's abandon this one, doesn't work correctly and it looks like the others have picked up on this as well :-)

**Pull request closed without merging**
